using DomainSchemas;
using System.Text.Json.Serialization;

namespace PlatformCore;

public sealed record ModuleSummary(string Name, string Version, string Description);

public sealed record AgentSummary(string Id, string Name, string Role, string Visibility);

public sealed record SkillSummary(string Name, string Description);

public sealed record WorkerSummary(string Name, string TargetSystem);

public sealed record ModuleStructureCheck(
    string ModuleName,
    bool Passed,
    IReadOnlyList<string> MissingEntries);

public sealed record PlatformSelfCheckReport(
    IReadOnlyList<ModuleSummary> RegisteredModules,
    IReadOnlyList<AgentSummary> RegisteredAgents,
    IReadOnlyList<AgentSummary> PublicAgents,
    IReadOnlyList<AgentSummary> InternalAgents,
    IReadOnlyList<SkillSummary> RegisteredSkills,
    IReadOnlyList<WorkerSummary> RegisteredWorkers,
    IReadOnlyList<WorkflowStepResult> WorkflowSteps,
    GateDecision GateDecision,
    IReadOnlyList<AgentDirectoryEntry> GatewayVisibleAgents,
    IReadOnlyList<AuditLogEntry> AuditLogs,
    bool SolutionExists,
    IReadOnlyList<ModuleStructureCheck> ModuleStructureChecks,
    string ModuleManifestSource,
    IReadOnlyList<string> YamlLoadedModules,
    IReadOnlyList<string> FallbackModules,
    bool GatewayQualityGateEnabled,
    bool StorageContractsRegistered,
    bool RejectReportBuilderCheck,
    bool InternalRoutingEnabled,
    IReadOnlyList<string> InternalAgentsInvoked,
    bool CollaborationReportCreated,
    bool GatewayBlocksInternalAgents,
    bool QualityGateAfterCollaboration,
    bool AuditInternalAgentCalls,
    bool AgentRuntimeProjectExists,
    bool MicrosoftRuntimeDependencyIsolated,
    string RuntimeMode,
    bool MockRuntimeAgentCreation,
    bool MicrosoftAgentAdapterCheck,
    bool MicrosoftWorkflowRuntimeCheck,
    bool RuntimeTypesDoNotLeakToContracts,
    bool GatewayVisibilityStillValid,
    bool QualityGateStillEnabled,
    bool WorkflowQualityLoopEnabled,
    string WorkflowPassedScenario,
    string WorkflowRejectedRetryPassedScenario,
    string WorkflowRejectedMaxRetriesScenario,
    string WorkflowHumanApprovalScenario,
    bool RetryPolicyEnabled,
    bool FailureReportGenerated,
    bool HumanApprovalRequestGenerated,
    bool ModuleAgentsRegistered,
    bool PlaceholderAgentIsFallbackOnly,
    bool ChiefEngineerInternalOrchestrationUsesWorkflowEngine,
    bool InternalAgentWorkflowStepsCreated,
    bool QualityGateAfterEachInternalStep,
    string InternalWorkflowPassedScenario,
    string InternalWorkflowRetryThenPassedScenario,
    string InternalWorkflowMaxRetriesExceededScenario,
    string InternalWorkflowFailedScenario,
    string InternalWorkflowHumanApprovalScenario,
    bool RetryPolicyInterfaceEnabled,
    bool ExponentialBackoffPolicyAvailable,
    bool CodeEngineerAgentRegistered,
    bool CodeReviewerAgentRegistered,
    bool CodeAgentsAreInternal,
    bool GatewayBlocksCodeAgents,
    bool RealRuntimeInvokerImplemented,
    bool RuntimeConfigEnvSupported,
    bool RuntimeModeDefaultIsMock,
    bool RuntimeFallbackWhenMissingKey,
    bool ChiefEngineerRealRuntimeOnly,
    bool InternalAgentsRemainMock,
    bool MicrosoftAgentOutputMapperEnabled,
    bool InvalidModelOutputFallbackEnabled,
    bool ModelCannotEscalatePermissions,
    bool ModelCannotCallWorkerDirectly,
    bool ChiefEngineerRuntimeThenWorkflowEngine,
    bool QualityGateAfterRealRuntime,
    bool GatewayResponseContainsRuntimeMetadata,
    bool MicrosoftRuntimeSmokeTestAttempted,
    bool MicrosoftRuntimeSmokeTestPassed,
    string? MicrosoftRuntimeSmokeTestError,
    bool RetryDelayActuallyAwaited,
    bool ExponentialBackoffDelayRespected,
    bool WorkflowRetryDelayCancellationSupported,
    bool RuntimeTimeoutConfigSupported,
    bool InvalidTimeoutFallsBackToDefault,
    [property: JsonPropertyName("openai_client_timeout_configured")] bool OpenAIClientTimeoutConfigured,
    [property: JsonPropertyName("openai_client_cancellation_supported")] bool OpenAIClientCancellationSupported,
    bool ProviderErrorsAreStructured,
    bool ApiKeyNotLogged,
    bool MarkdownChineseStandardExists,
    int MarkdownFilesScanned,
    bool MarkdownChineseValidatorEnabled,
    bool MarkdownChineseCheckPassed,
    bool MarkdownLanguageReportGenerated,
    bool MarkdownEnglishExceptionsSupported,
    [property: JsonPropertyName("solidworks_module_skeleton_enabled")] bool SolidWorksModuleSkeletonEnabled,
    [property: JsonPropertyName("solidworks_build_plan_skill_registered")] bool SolidWorksBuildPlanSkillRegistered,
    [property: JsonPropertyName("solidworks_build_plan_generated")] bool SolidWorksBuildPlanGenerated,
    [property: JsonPropertyName("solidworks_worker_contract_exists")] bool SolidWorksWorkerContractExists,
    [property: JsonPropertyName("fake_solidworks_worker_registered")] bool FakeSolidWorksWorkerRegistered,
    [property: JsonPropertyName("fake_solidworks_worker_dry_run_passed")] bool FakeSolidWorksWorkerDryRunPassed,
    [property: JsonPropertyName("solidworks_build_plan_validator_passed")] bool SolidWorksBuildPlanValidatorPassed,
    [property: JsonPropertyName("solidworks_artifact_validator_passed")] bool SolidWorksArtifactValidatorPassed,
    [property: JsonPropertyName("solidworks_build_plan_reviewer_passed")] bool SolidWorksBuildPlanReviewerPassed,
    [property: JsonPropertyName("solidworks_quality_gate_passed")] bool SolidWorksQualityGatePassed,
    [property: JsonPropertyName("solidworks_fake_artifacts_generated")] bool SolidWorksFakeArtifactsGenerated,
    [property: JsonPropertyName("solidworks_real_cad_not_executed")] bool SolidWorksRealCadNotExecuted,
    [property: JsonPropertyName("solidworks_agent_does_not_call_worker_directly")] bool SolidWorksAgentDoesNotCallWorkerDirectly,
    [property: JsonPropertyName("gateway_does_not_call_solidworks_worker")] bool GatewayDoesNotCallSolidWorksWorker,
    [property: JsonPropertyName("solidworks_self_check_error")] string? SolidWorksSelfCheckError,
    [property: JsonPropertyName("solidworks_real_worker_skeleton_exists")] bool SolidWorksRealWorkerSkeletonExists,
    [property: JsonPropertyName("solidworks_environment_validator_exists")] bool SolidWorksEnvironmentValidatorExists,
    [property: JsonPropertyName("solidworks_preflight_report_generated")] bool SolidWorksPreflightReportGenerated,
    [property: JsonPropertyName("solidworks_session_manager_exists")] bool SolidWorksSessionManagerExists,
    [property: JsonPropertyName("solidworks_real_execution_default_disabled")] bool SolidWorksRealExecutionDefaultDisabled,
    [property: JsonPropertyName("solidworks_real_execution_requires_request_flag")] bool SolidWorksRealExecutionRequiresRequestFlag,
    [property: JsonPropertyName("solidworks_real_execution_requires_env_flag")] bool SolidWorksRealExecutionRequiresEnvFlag,
    [property: JsonPropertyName("solidworks_com_not_called_in_default_self_check")] bool SolidWorksComNotCalledInDefaultSelfCheck,
    [property: JsonPropertyName("solidworks_real_connection_smoke_test_attempted")] bool SolidWorksRealConnectionSmokeTestAttempted,
    [property: JsonPropertyName("solidworks_real_connection_smoke_test_passed")] bool SolidWorksRealConnectionSmokeTestPassed,
    [property: JsonPropertyName("solidworks_real_connection_smoke_test_error")] string? SolidWorksRealConnectionSmokeTestError,
    [property: JsonPropertyName("solidworks_generic_real_build_not_implemented")] bool SolidWorksGenericRealBuildNotImplemented,
    [property: JsonPropertyName("solidworks_real_cad_not_executed_by_default")] bool SolidWorksRealCadNotExecutedByDefault,
    [property: JsonPropertyName("solidworks_real_plate_build_implemented")] bool SolidWorksRealPlateBuildImplemented,
    [property: JsonPropertyName("solidworks_real_build_requires_env_flag")] bool SolidWorksRealBuildRequiresEnvFlag,
    [property: JsonPropertyName("solidworks_real_build_requires_request_flag")] bool SolidWorksRealBuildRequiresRequestFlag,
    [property: JsonPropertyName("solidworks_real_build_requires_dry_run_false")] bool SolidWorksRealBuildRequiresDryRunFalse,
    [property: JsonPropertyName("solidworks_real_build_default_disabled")] bool SolidWorksRealBuildDefaultDisabled,
    [property: JsonPropertyName("solidworks_real_build_smoke_test_attempted")] bool SolidWorksRealBuildSmokeTestAttempted,
    [property: JsonPropertyName("solidworks_real_build_smoke_test_passed")] bool SolidWorksRealBuildSmokeTestPassed,
    [property: JsonPropertyName("solidworks_real_build_smoke_test_error")] string? SolidWorksRealBuildSmokeTestError,
    [property: JsonPropertyName("solidworks_real_build_artifacts_validated")] bool SolidWorksRealBuildArtifactsValidated,
    [property: JsonPropertyName("solidworks_real_build_report_generated")] bool SolidWorksRealBuildReportGenerated,
    [property: JsonPropertyName("solidworks_real_build_outputs_sldprt")] bool SolidWorksRealBuildOutputsSldprt,
    [property: JsonPropertyName("solidworks_real_build_outputs_step")] bool SolidWorksRealBuildOutputsStep,
    [property: JsonPropertyName("solidworks_real_build_outputs_json_report")] bool SolidWorksRealBuildOutputsJsonReport,
    [property: JsonPropertyName("solidworks_real_build_not_called_in_default_self_check")] bool SolidWorksRealBuildNotCalledInDefaultSelfCheck,
    string FinalStatus);
