using DomainSchemas;
using System.Text.Json.Serialization;

namespace PlatformCore;

public sealed record ModuleSummary(string Name, string Version, string Description);

public sealed record AgentSummary(string Id, string Name, string Role, string Visibility);

public sealed record SkillSummary(string Name, string Description);

public sealed record WorkerSummary(string Name, string TargetSystem);

public sealed record ModuleStructureCheck(
    string ModuleName,
    bool Passed,
    IReadOnlyList<string> MissingEntries);

public sealed record PlatformSelfCheckReport(
    IReadOnlyList<ModuleSummary> RegisteredModules,
    IReadOnlyList<AgentSummary> RegisteredAgents,
    IReadOnlyList<AgentSummary> PublicAgents,
    IReadOnlyList<AgentSummary> InternalAgents,
    IReadOnlyList<SkillSummary> RegisteredSkills,
    IReadOnlyList<WorkerSummary> RegisteredWorkers,
    IReadOnlyList<WorkflowStepResult> WorkflowSteps,
    GateDecision GateDecision,
    IReadOnlyList<AgentDirectoryEntry> GatewayVisibleAgents,
    IReadOnlyList<AuditLogEntry> AuditLogs,
    bool SolutionExists,
    IReadOnlyList<ModuleStructureCheck> ModuleStructureChecks,
    string ModuleManifestSource,
    IReadOnlyList<string> YamlLoadedModules,
    IReadOnlyList<string> FallbackModules,
    bool GatewayQualityGateEnabled,
    bool StorageContractsRegistered,
    bool RejectReportBuilderCheck,
    bool InternalRoutingEnabled,
    IReadOnlyList<string> InternalAgentsInvoked,
    bool CollaborationReportCreated,
    bool GatewayBlocksInternalAgents,
    bool QualityGateAfterCollaboration,
    bool AuditInternalAgentCalls,
    bool AgentRuntimeProjectExists,
    bool MicrosoftRuntimeDependencyIsolated,
    string RuntimeMode,
    bool MockRuntimeAgentCreation,
    bool MicrosoftAgentAdapterCheck,
    bool MicrosoftWorkflowRuntimeCheck,
    bool RuntimeTypesDoNotLeakToContracts,
    bool GatewayVisibilityStillValid,
    bool QualityGateStillEnabled,
    bool WorkflowQualityLoopEnabled,
    string WorkflowPassedScenario,
    string WorkflowRejectedRetryPassedScenario,
    string WorkflowRejectedMaxRetriesScenario,
    string WorkflowHumanApprovalScenario,
    bool RetryPolicyEnabled,
    bool FailureReportGenerated,
    bool HumanApprovalRequestGenerated,
    bool ModuleAgentsRegistered,
    bool PlaceholderAgentIsFallbackOnly,
    bool ChiefEngineerInternalOrchestrationUsesWorkflowEngine,
    bool InternalAgentWorkflowStepsCreated,
    bool QualityGateAfterEachInternalStep,
    string InternalWorkflowPassedScenario,
    string InternalWorkflowRetryThenPassedScenario,
    string InternalWorkflowMaxRetriesExceededScenario,
    string InternalWorkflowFailedScenario,
    string InternalWorkflowHumanApprovalScenario,
    bool RetryPolicyInterfaceEnabled,
    bool ExponentialBackoffPolicyAvailable,
    bool CodeEngineerAgentRegistered,
    bool CodeReviewerAgentRegistered,
    bool CodeAgentsAreInternal,
    bool GatewayBlocksCodeAgents,
    bool RealRuntimeInvokerImplemented,
    bool RuntimeConfigEnvSupported,
    bool RuntimeModeDefaultIsMock,
    bool RuntimeFallbackWhenMissingKey,
    bool ChiefEngineerRealRuntimeOnly,
    bool InternalAgentsRemainMock,
    bool MicrosoftAgentOutputMapperEnabled,
    bool InvalidModelOutputFallbackEnabled,
    bool ModelCannotEscalatePermissions,
    bool ModelCannotCallWorkerDirectly,
    bool ChiefEngineerRuntimeThenWorkflowEngine,
    bool QualityGateAfterRealRuntime,
    bool GatewayResponseContainsRuntimeMetadata,
    bool MicrosoftRuntimeSmokeTestAttempted,
    bool MicrosoftRuntimeSmokeTestPassed,
    string? MicrosoftRuntimeSmokeTestError,
    bool RetryDelayActuallyAwaited,
    bool ExponentialBackoffDelayRespected,
    bool WorkflowRetryDelayCancellationSupported,
    bool RuntimeTimeoutConfigSupported,
    bool InvalidTimeoutFallsBackToDefault,
    [property: JsonPropertyName("openai_client_timeout_configured")] bool OpenAIClientTimeoutConfigured,
    [property: JsonPropertyName("openai_client_cancellation_supported")] bool OpenAIClientCancellationSupported,
    bool ProviderErrorsAreStructured,
    bool ApiKeyNotLogged,
    bool MarkdownChineseStandardExists,
    int MarkdownFilesScanned,
    bool MarkdownChineseValidatorEnabled,
    bool MarkdownChineseCheckPassed,
    bool MarkdownLanguageReportGenerated,
    bool MarkdownEnglishExceptionsSupported,
    [property: JsonPropertyName("solidworks_module_skeleton_enabled")] bool SolidWorksModuleSkeletonEnabled,
    [property: JsonPropertyName("solidworks_build_plan_skill_registered")] bool SolidWorksBuildPlanSkillRegistered,
    [property: JsonPropertyName("solidworks_build_plan_generated")] bool SolidWorksBuildPlanGenerated,
    [property: JsonPropertyName("solidworks_worker_contract_exists")] bool SolidWorksWorkerContractExists,
    [property: JsonPropertyName("fake_solidworks_worker_registered")] bool FakeSolidWorksWorkerRegistered,
    [property: JsonPropertyName("fake_solidworks_worker_dry_run_passed")] bool FakeSolidWorksWorkerDryRunPassed,
    [property: JsonPropertyName("solidworks_build_plan_validator_passed")] bool SolidWorksBuildPlanValidatorPassed,
    [property: JsonPropertyName("solidworks_artifact_validator_passed")] bool SolidWorksArtifactValidatorPassed,
    [property: JsonPropertyName("solidworks_build_plan_reviewer_passed")] bool SolidWorksBuildPlanReviewerPassed,
    [property: JsonPropertyName("solidworks_quality_gate_passed")] bool SolidWorksQualityGatePassed,
    [property: JsonPropertyName("solidworks_fake_artifacts_generated")] bool SolidWorksFakeArtifactsGenerated,
    [property: JsonPropertyName("solidworks_real_cad_not_executed")] bool SolidWorksRealCadNotExecuted,
    [property: JsonPropertyName("solidworks_agent_does_not_call_worker_directly")] bool SolidWorksAgentDoesNotCallWorkerDirectly,
    [property: JsonPropertyName("gateway_does_not_call_solidworks_worker")] bool GatewayDoesNotCallSolidWorksWorker,
    [property: JsonPropertyName("solidworks_self_check_error")] string? SolidWorksSelfCheckError,
    [property: JsonPropertyName("solidworks_real_worker_skeleton_exists")] bool SolidWorksRealWorkerSkeletonExists,
    [property: JsonPropertyName("solidworks_environment_validator_exists")] bool SolidWorksEnvironmentValidatorExists,
    [property: JsonPropertyName("solidworks_preflight_report_generated")] bool SolidWorksPreflightReportGenerated,
    [property: JsonPropertyName("solidworks_session_manager_exists")] bool SolidWorksSessionManagerExists,
    [property: JsonPropertyName("solidworks_real_execution_default_disabled")] bool SolidWorksRealExecutionDefaultDisabled,
    [property: JsonPropertyName("solidworks_real_execution_requires_request_flag")] bool SolidWorksRealExecutionRequiresRequestFlag,
    [property: JsonPropertyName("solidworks_real_execution_requires_env_flag")] bool SolidWorksRealExecutionRequiresEnvFlag,
    [property: JsonPropertyName("solidworks_com_not_called_in_default_self_check")] bool SolidWorksComNotCalledInDefaultSelfCheck,
    [property: JsonPropertyName("solidworks_real_connection_smoke_test_attempted")] bool SolidWorksRealConnectionSmokeTestAttempted,
    [property: JsonPropertyName("solidworks_real_connection_smoke_test_passed")] bool SolidWorksRealConnectionSmokeTestPassed,
    [property: JsonPropertyName("solidworks_real_connection_smoke_test_error")] string? SolidWorksRealConnectionSmokeTestError,
    [property: JsonPropertyName("solidworks_generic_real_build_not_implemented")] bool SolidWorksGenericRealBuildNotImplemented,
    [property: JsonPropertyName("solidworks_real_cad_not_executed_by_default")] bool SolidWorksRealCadNotExecutedByDefault,
    [property: JsonPropertyName("solidworks_real_plate_build_implemented")] bool SolidWorksRealPlateBuildImplemented,
    [property: JsonPropertyName("solidworks_real_build_requires_env_flag")] bool SolidWorksRealBuildRequiresEnvFlag,
    [property: JsonPropertyName("solidworks_real_build_requires_request_flag")] bool SolidWorksRealBuildRequiresRequestFlag,
    [property: JsonPropertyName("solidworks_real_build_requires_dry_run_false")] bool SolidWorksRealBuildRequiresDryRunFalse,
    [property: JsonPropertyName("solidworks_real_build_default_disabled")] bool SolidWorksRealBuildDefaultDisabled,
    [property: JsonPropertyName("solidworks_real_build_smoke_test_attempted")] bool SolidWorksRealBuildSmokeTestAttempted,
    [property: JsonPropertyName("solidworks_real_build_smoke_test_passed")] bool SolidWorksRealBuildSmokeTestPassed,
    [property: JsonPropertyName("solidworks_real_build_smoke_test_error")] string? SolidWorksRealBuildSmokeTestError,
    [property: JsonPropertyName("solidworks_real_build_artifacts_validated")] bool SolidWorksRealBuildArtifactsValidated,
    [property: JsonPropertyName("solidworks_real_build_report_generated")] bool SolidWorksRealBuildReportGenerated,
    [property: JsonPropertyName("solidworks_real_build_outputs_sldprt")] bool SolidWorksRealBuildOutputsSldprt,
    [property: JsonPropertyName("solidworks_real_build_outputs_step")] bool SolidWorksRealBuildOutputsStep,
    [property: JsonPropertyName("solidworks_real_build_outputs_json_report")] bool SolidWorksRealBuildOutputsJsonReport,
    [property: JsonPropertyName("solidworks_real_build_not_called_in_default_self_check")] bool SolidWorksRealBuildNotCalledInDefaultSelfCheck,
    [property: JsonPropertyName("sw_enable_real_execution_env_value")] string? SwEnableRealExecutionEnvValue,
    [property: JsonPropertyName("sw_real_build_smoke_test_env_value")] string? SwRealBuildSmokeTestEnvValue,
    [property: JsonPropertyName("sw_strict_real_build_test_env_value")] string? SwStrictRealBuildTestEnvValue,
    [property: JsonPropertyName("real_build_request_dry_run")] bool? RealBuildRequestDryRun,
    [property: JsonPropertyName("real_build_request_allow_real_cad_execution")] bool? RealBuildRequestAllowRealCadExecution,
    [property: JsonPropertyName("real_build_execution_mode")] string? RealBuildExecutionMode,
    [property: JsonPropertyName("real_build_output_directory")] string? RealBuildOutputDirectory,
    [property: JsonPropertyName("real_build_latest_report_path")] string? RealBuildLatestReportPath,
    [property: JsonPropertyName("solidworks_diagnostic_runner_exists")] bool SolidWorksDiagnosticRunnerExists,
    [property: JsonPropertyName("solidworks_diagnostic_runner_not_called_by_default")] bool SolidWorksDiagnosticRunnerNotCalledByDefault,
    [property: JsonPropertyName("solidworks_latest_diagnostic_report_path")] string? SolidWorksLatestDiagnosticReportPath,
    [property: JsonPropertyName("solidworks_latest_diagnostic_final_status")] string? SolidWorksLatestDiagnosticFinalStatus,
    [property: JsonPropertyName("solidworks_real_build_failure_stage")] string? SolidWorksRealBuildFailureStage,
    [property: JsonPropertyName("solidworks_real_build_error_is_actionable")] bool SolidWorksRealBuildErrorIsActionable,
    [property: JsonPropertyName("solidworks_api_failure_analyzer_exists")] bool SolidWorksApiFailureAnalyzerExists,
    [property: JsonPropertyName("solidworks_api_evidence_collector_exists")] bool SolidWorksApiEvidenceCollectorExists,
    [property: JsonPropertyName("solidworks_api_evidence_report_schema_exists")] bool SolidWorksApiEvidenceReportSchemaExists,
    [property: JsonPropertyName("solidworks_cut_holes_api_evidence_supported")] bool SolidWorksCutHolesApiEvidenceSupported,
    [property: JsonPropertyName("solidworks_reference_skill_readonly_analysis_supported")] bool SolidWorksReferenceSkillReadonlyAnalysisSupported,
    [property: JsonPropertyName("solidworks_external_scripts_not_copied")] bool SolidWorksExternalScriptsNotCopied,
    [property: JsonPropertyName("solidworks_api_repair_loop_available")] bool SolidWorksApiRepairLoopAvailable,
    [property: JsonPropertyName("solidworks_macro_recording_request_available")] bool SolidWorksMacroRecordingRequestAvailable,
    [property: JsonPropertyName("solidworks_plate_feature_builder_exists")] bool SolidWorksPlateFeatureBuilderExists,
    [property: JsonPropertyName("solidworks_real_drawing_basic_views_implemented")] bool SolidWorksRealDrawingBasicViewsImplemented,
    [property: JsonPropertyName("solidworks_real_drawing_default_disabled")] bool SolidWorksRealDrawingDefaultDisabled,
    [property: JsonPropertyName("solidworks_real_drawing_requires_env_flag")] bool SolidWorksRealDrawingRequiresEnvFlag,
    [property: JsonPropertyName("solidworks_real_drawing_smoke_test_attempted")] bool SolidWorksRealDrawingSmokeTestAttempted,
    [property: JsonPropertyName("solidworks_real_drawing_smoke_test_passed")] bool SolidWorksRealDrawingSmokeTestPassed,
    [property: JsonPropertyName("solidworks_real_drawing_smoke_test_error")] string? SolidWorksRealDrawingSmokeTestError,
    [property: JsonPropertyName("solidworks_real_drawing_outputs_slddrw")] bool SolidWorksRealDrawingOutputsSlddrw,
    [property: JsonPropertyName("solidworks_real_drawing_outputs_pdf")] bool SolidWorksRealDrawingOutputsPdf,
    [property: JsonPropertyName("solidworks_real_drawing_outputs_json_report")] bool SolidWorksRealDrawingOutputsJsonReport,
    [property: JsonPropertyName("solidworks_real_drawing_not_called_in_default_self_check")] bool SolidWorksRealDrawingNotCalledInDefaultSelfCheck,
    [property: JsonPropertyName("solidworks_drawing_report_generated")] bool SolidWorksDrawingReportGenerated,
    [property: JsonPropertyName("solidworks_real_drawing_failure_stage")] string? SolidWorksRealDrawingFailureStage,
    [property: JsonPropertyName("solidworks_drawing_failure_stage_actionable")] bool SolidWorksDrawingFailureStageActionable,
    [property: JsonPropertyName("real_drawing_output_directory")] string? RealDrawingOutputDirectory,
    [property: JsonPropertyName("real_drawing_latest_report_path")] string? RealDrawingLatestReportPath,
    [property: JsonPropertyName("v1_1_version_stage_documented")] bool V11VersionStageDocumented,
    [property: JsonPropertyName("solidworks_drawing_failure_repair_documented")] bool SolidWorksDrawingFailureRepairDocumented,
    [property: JsonPropertyName("solidworks_drawing_api_evidence_documented")] bool SolidWorksDrawingApiEvidenceDocumented,
    [property: JsonPropertyName("solidworks_drawing_review_checklist_updated")] bool SolidWorksDrawingReviewChecklistUpdated,
    [property: JsonPropertyName("executable_docs_layer_enabled")] bool ExecutableDocsLayerEnabled,
    [property: JsonPropertyName("docs_index_exists")] bool DocsIndexExists,
    [property: JsonPropertyName("project_execution_standard_exists")] bool ProjectExecutionStandardExists,
    [property: JsonPropertyName("module_document_standard_exists")] bool ModuleDocumentStandardExists,
    [property: JsonPropertyName("step_execution_standard_exists")] bool StepExecutionStandardExists,
    [property: JsonPropertyName("failure_repair_standard_exists")] bool FailureRepairStandardExists,
    [property: JsonPropertyName("codex_execution_protocol_exists")] bool CodexExecutionProtocolExists,
    [property: JsonPropertyName("claude_review_protocol_exists")] bool ClaudeReviewProtocolExists,
    [property: JsonPropertyName("version_stage_index_exists")] bool VersionStageIndexExists,
    [property: JsonPropertyName("codex_agent_team_guide_exists")] bool CodexAgentTeamGuideExists,
    [property: JsonPropertyName("codex_agent_registry_exists")] bool CodexAgentRegistryExists,
    [property: JsonPropertyName("codex_agent_governance_doc_exists")] bool CodexAgentGovernanceDocExists,
    [property: JsonPropertyName("agents_md_exists")] bool AgentsMdExists,
    [property: JsonPropertyName("codex_agents_configured")] bool CodexAgentsConfigured,
    [property: JsonPropertyName("codex_agent_registry_lists_canonical_agents")] bool CodexAgentRegistryListsCanonicalAgents,
    [property: JsonPropertyName("codex_no_duplicate_active_agents")] bool CodexNoDuplicateActiveAgents,
    [property: JsonPropertyName("codex_agent_reuse_policy_documented")] bool CodexAgentReusePolicyDocumented,
    [property: JsonPropertyName("codex_agent_new_requirements_go_to_skills_or_docs")] bool CodexAgentNewRequirementsGoToSkillsOrDocs,
    [property: JsonPropertyName("codex_active_agent_count_is_expected")] bool CodexActiveAgentCountIsExpected,
    [property: JsonPropertyName("codex_only_canonical_agents_active")] bool CodexOnlyCanonicalAgentsActive,
    [property: JsonPropertyName("codex_config_example_exists")] bool CodexConfigExampleExists,
    [property: JsonPropertyName("codex_project_manager_agent_exists")] bool CodexProjectManagerAgentExists,
    [property: JsonPropertyName("codex_code_mapper_agent_exists")] bool CodexCodeMapperAgentExists,
    [property: JsonPropertyName("codex_api_researcher_agent_exists")] bool CodexApiResearcherAgentExists,
    [property: JsonPropertyName("codex_cad_worker_agent_exists")] bool CodexCadWorkerAgentExists,
    [property: JsonPropertyName("codex_quality_gate_agent_exists")] bool CodexQualityGateAgentExists,
    [property: JsonPropertyName("codex_docs_writer_agent_exists")] bool CodexDocsWriterAgentExists,
    [property: JsonPropertyName("codex_agents_do_not_replace_project_modules")] bool CodexAgentsDoNotReplaceProjectModules,
    [property: JsonPropertyName("codex_agents_respect_worker_boundaries")] bool CodexAgentsRespectWorkerBoundaries,
    [property: JsonPropertyName("agents_skills_directory_exists")] bool AgentsSkillsDirectoryExists,
    [property: JsonPropertyName("solidworks_api_repair_skill_exists")] bool SolidWorksApiRepairSkillExists,
    [property: JsonPropertyName("markdown_docs_standard_skill_exists")] bool MarkdownDocsStandardSkillExists,
    [property: JsonPropertyName("quality_review_skill_exists")] bool QualityReviewSkillExists,
    [property: JsonPropertyName("cadmodeling_execution_doc_exists")] bool CadModelingExecutionDocExists,
    [property: JsonPropertyName("cadmodeling_failure_repair_doc_exists")] bool CadModelingFailureRepairDocExists,
    [property: JsonPropertyName("cadmodeling_api_evidence_doc_exists")] bool CadModelingApiEvidenceDocExists,
    [property: JsonPropertyName("cadmodeling_review_checklist_exists")] bool CadModelingReviewChecklistExists,
    [property: JsonPropertyName("solidworks_worker_execution_doc_exists")] bool SolidWorksWorkerExecutionDocExists,
    [property: JsonPropertyName("solidworks_worker_failure_repair_doc_exists")] bool SolidWorksWorkerFailureRepairDocExists,
    [property: JsonPropertyName("solidworks_worker_api_evidence_doc_exists")] bool SolidWorksWorkerApiEvidenceDocExists,
    [property: JsonPropertyName("solidworks_worker_review_checklist_exists")] bool SolidWorksWorkerReviewChecklistExists,
    string FinalStatus);
