using DomainSchemas;
using System.Text.Json.Serialization;

namespace PlatformCore;

public sealed record ModuleSummary(string Name, string Version, string Description);

public sealed record AgentSummary(string Id, string Name, string Role, string Visibility);

public sealed record SkillSummary(string Name, string Description);

public sealed record WorkerSummary(string Name, string TargetSystem);

public sealed record ModuleStructureCheck(
    string ModuleName,
    bool Passed,
    IReadOnlyList<string> MissingEntries);

public sealed record PlatformSelfCheckReport(
    IReadOnlyList<ModuleSummary> RegisteredModules,
    IReadOnlyList<AgentSummary> RegisteredAgents,
    IReadOnlyList<AgentSummary> PublicAgents,
    IReadOnlyList<AgentSummary> InternalAgents,
    IReadOnlyList<SkillSummary> RegisteredSkills,
    IReadOnlyList<WorkerSummary> RegisteredWorkers,
    IReadOnlyList<WorkflowStepResult> WorkflowSteps,
    GateDecision GateDecision,
    IReadOnlyList<AgentDirectoryEntry> GatewayVisibleAgents,
    IReadOnlyList<AuditLogEntry> AuditLogs,
    bool SolutionExists,
    IReadOnlyList<ModuleStructureCheck> ModuleStructureChecks,
    string ModuleManifestSource,
    IReadOnlyList<string> YamlLoadedModules,
    IReadOnlyList<string> FallbackModules,
    bool GatewayQualityGateEnabled,
    bool StorageContractsRegistered,
    bool RejectReportBuilderCheck,
    bool InternalRoutingEnabled,
    IReadOnlyList<string> InternalAgentsInvoked,
    bool CollaborationReportCreated,
    bool GatewayBlocksInternalAgents,
    bool QualityGateAfterCollaboration,
    bool AuditInternalAgentCalls,
    bool AgentRuntimeProjectExists,
    bool MicrosoftRuntimeDependencyIsolated,
    string RuntimeMode,
    bool MockRuntimeAgentCreation,
    bool MicrosoftAgentAdapterCheck,
    bool MicrosoftWorkflowRuntimeCheck,
    bool RuntimeTypesDoNotLeakToContracts,
    bool GatewayVisibilityStillValid,
    bool QualityGateStillEnabled,
    bool WorkflowQualityLoopEnabled,
    string WorkflowPassedScenario,
    string WorkflowRejectedRetryPassedScenario,
    string WorkflowRejectedMaxRetriesScenario,
    string WorkflowHumanApprovalScenario,
    bool RetryPolicyEnabled,
    bool FailureReportGenerated,
    bool HumanApprovalRequestGenerated,
    bool ModuleAgentsRegistered,
    bool PlaceholderAgentIsFallbackOnly,
    bool ChiefEngineerInternalOrchestrationUsesWorkflowEngine,
    bool InternalAgentWorkflowStepsCreated,
    bool QualityGateAfterEachInternalStep,
    string InternalWorkflowPassedScenario,
    string InternalWorkflowRetryThenPassedScenario,
    string InternalWorkflowMaxRetriesExceededScenario,
    string InternalWorkflowFailedScenario,
    string InternalWorkflowHumanApprovalScenario,
    bool RetryPolicyInterfaceEnabled,
    bool ExponentialBackoffPolicyAvailable,
    bool CodeEngineerAgentRegistered,
    bool CodeReviewerAgentRegistered,
    bool CodeAgentsAreInternal,
    bool GatewayBlocksCodeAgents,
    bool RealRuntimeInvokerImplemented,
    bool RuntimeConfigEnvSupported,
    bool RuntimeModeDefaultIsMock,
    bool RuntimeFallbackWhenMissingKey,
    bool ChiefEngineerRealRuntimeOnly,
    bool InternalAgentsRemainMock,
    bool MicrosoftAgentOutputMapperEnabled,
    bool InvalidModelOutputFallbackEnabled,
    bool ModelCannotEscalatePermissions,
    bool ModelCannotCallWorkerDirectly,
    bool ChiefEngineerRuntimeThenWorkflowEngine,
    bool QualityGateAfterRealRuntime,
    bool GatewayResponseContainsRuntimeMetadata,
    bool MicrosoftRuntimeSmokeTestAttempted,
    bool MicrosoftRuntimeSmokeTestPassed,
    string? MicrosoftRuntimeSmokeTestError,
    bool RetryDelayActuallyAwaited,
    bool ExponentialBackoffDelayRespected,
    bool WorkflowRetryDelayCancellationSupported,
    bool RuntimeTimeoutConfigSupported,
    bool InvalidTimeoutFallsBackToDefault,
    [property: JsonPropertyName("openai_client_timeout_configured")] bool OpenAIClientTimeoutConfigured,
    [property: JsonPropertyName("openai_client_cancellation_supported")] bool OpenAIClientCancellationSupported,
    bool ProviderErrorsAreStructured,
    bool ApiKeyNotLogged,
    bool MarkdownChineseStandardExists,
    int MarkdownFilesScanned,
    bool MarkdownChineseValidatorEnabled,
    bool MarkdownChineseCheckPassed,
    bool MarkdownLanguageReportGenerated,
    bool MarkdownEnglishExceptionsSupported,
    string FinalStatus);
